In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
path = '../data/Preprocessed_data.csv'
df4 = pd.read_csv(path)

In [3]:
df4.head()

,Unnamed: 0,user_id,location,age,isbn,rating,book_title,book_author,year_of_publication,publisher,img_s,img_m,img_l,Summary,Language,Category,city,state,country
0,0,2,"stockton, california, usa",18.0000,0195153448,0,Classical Mythology,Mark P. O. Morford,2002.0,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,Provides an introduction to classical myths pl...,en,['Social Science'],stockton,california,usa
1,1,8,"timmins, ontario, canada",34.7439,0002005018,5,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],timmins,ontario,canada
2,2,11400,"ottawa, ontario, canada",49.0000,0002005018,0,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],ottawa,ontario,canada
3,3,11676,"n/a, n/a, n/a",34.7439,0002005018,8,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],NaN,NaN,NaN
4,4,41385,"sudbury, ontario, canada",34.7439,0002005018,0,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],sudbury,ontario,canada

In [4]:
dfg = df4.groupby(['country', 'isbn', 'img_s', 'img_l', 'book_title']).agg({'user_id': 'count', 'rating': 'mean'})
dfg['log_user_id_cnt'] = dfg['user_id'].apply(lambda x: math.log(x, 2))

user_cnt_max = dfg['log_user_id_cnt'].max()
rating_max = dfg['rating'].max()
dfg['weight'] = dfg[['log_user_id_cnt', 'rating']].apply(lambda x: x[0] / user_cnt_max * 70 + x[1] / rating_max * 30, axis=1)

In [5]:
g = dfg['weight'].groupby('country', group_keys=False)

In [6]:
res = g.apply(lambda x: x.sort_values(ascending=False))

In [7]:
res = res.reset_index()

In [8]:
res.head()

,country,isbn,img_s,img_l,book_title,weight
0,",",0385484518,http://images.amazon.com/images/P/0385484518.0...,http://images.amazon.com/images/P/0385484518.0...,"Tuesdays with Morrie: An Old Man, a Young Man,...",30.0
1,",",0312961324,http://images.amazon.com/images/P/0312961324.0...,http://images.amazon.com/images/P/0312961324.0...,The Shell Seekers (Shell Seekers),30.0
2,",",0440226430,http://images.amazon.com/images/P/0440226430.0...,http://images.amazon.com/images/P/0440226430.0...,Summer Sisters,30.0
3,",",0553380095,http://images.amazon.com/images/P/0553380095.0...,http://images.amazon.com/images/P/0553380095.0...,The Heart of a Woman,27.0
4,",",0515109509,http://images.amazon.com/images/P/0515109509.0...,http://images.amazon.com/images/P/0515109509.0...,The Cat Who Moved a Mountain,27.0

In [9]:
# Output
res.to_csv('../data/region_score_sort.csv')